### ISSUE TITLE
Build failure..

### ISSUE THREAD

**Issue by jahagirdar** [cym0n/strehler#54]
I am trying to install the package on an clean VM (virtual box ) configured as per the instructions at
http://perlmaven.com/getting-started-with-perl-dancer-on-digital-ocean
with the following configuration
8GB Disk space 500Mb RAM
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015 i686 i686 i686 GNU/Linux
[build.log.zip](https://github.com/cym0n/strehler/files/89946/build.log.zip)

I am getting a failed status (log attached)

**Comment by cym0n** [comment]
Sorry, I can't retrieve the zip file. Can you paste here the relevant part of the log?

**Comment by jahagirdar** [comment]
[build.log.zip](https://github.com/cym0n/strehler/files/90214/build.log.zip)
(Reuploaded the log file)
Note there seems to be an open bug on cpan at
https://rt.cpan.org/Public/Dist/Display.html?Name=Strehler 
110567 	No pass reports with Dancer2 0.165000


The errors seen by me are

"/home/starman/perl5/perlbrew/perls/perl-5.22.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/strehler
Manifying 28 pod documents
Manifying 17 pod documents
PERL_DL_NONLAZY=1 "/home/starman/perl5/perlbrew/perls/perl-5.22.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/001_login.t ........ ok
[Strehler::Admin:25083] error @2016-01-14 14:40:12> Route exception: file error - 403.tt: not found in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1288

#   Failed test 'Editor cannot access categories'
#   at t/002_permissions.t line 31.
#          got: '500'
#     expected: '403'
# Looks like you failed 1 test of 3.
t/002_permissions.t ..
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests
t/004_categories.t ... ok
t/005_articles.t ..... ok
t/006_frontend.t ..... ok
t/007_images.t ....... ok
t/008_tags.t ......... ok
t/009_extra.t ........ ok
[Strehler::API:25090] error @2016-01-14 14:40:35> Route exception: file error - 404.tt: not found in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1288

#   Failed test 'Element not found'
#   at t/010_api.t line 119.
#          got: '500'
#     expected: '404'
[Strehler::API:25090] error @2016-01-14 14:40:35> Route exception: file error - 404.tt: not found in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1288

#   Failed test 'Element not found'
#   at t/010_api.t line 122.
#          got: '500'
#     expected: '404'
# Looks like you failed 2 tests of 25.
t/010_api.t ..........
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/25 subtests
[Site:25091] error @2016-01-14 14:40:37> Route exception: file error - 404.tt: not found in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1288

#   Failed test '404 returned when bad slug called'
#   at t/011_ex.t line 30.
#          got: '500'
#     expected: '404'
[Site:25091] error @2016-01-14 14:40:37> Route exception: file error - 404.tt: not found in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1288

#   Failed test '404 returned when bad slug called (parameters as hash)'
#   at t/011_ex.t line 36.
#          got: '500'
#     expected: '404'
# Looks like you failed 2 tests of 12.
t/011_ex.t ...........
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/12 subtests
t/012_users.t ........ ok

#   Failed test 'Dashboard with a not configured language returns 404'
#   at t/013_dashboard.t line 78.
#          got: '500'
#     expected: '404'
# Looks like you failed 1 test of 11.
t/013_dashboard.t ....
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/11 subtests
t/author-critic.t .... skipped: these tests are for testing by the author

Test Summary Report
-------------------
t/002_permissions.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
t/010_api.t        (Wstat: 512 Tests: 25 Failed: 2)
  Failed tests:  16-17
  Non-zero exit status: 2
t/011_ex.t         (Wstat: 512 Tests: 12 Failed: 2)
  Failed tests:  1, 4
  Non-zero exit status: 2
t/013_dashboard.t  (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  11
  Non-zero exit status: 1
Files=13, Tests=140, 38 wallclock secs ( 0.09 usr  0.13 sys + 20.81 cusr 11.03 csys = 32.06 CPU)
Result: FAIL
Failed 4/13 test programs. 6/140 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Strehler failed. See /home/starman/.cpanm/work/1452762509.24995/build.log for details. Retry with --force to force install it.

**Comment by cym0n** [comment]
Yeah, you're right.
In this period Dancer2 made many step forward and I hadn't the time to check if all this work broke my package... as it probably did.

I'll work on it!

**Comment by cym0n** [comment]
I released a new version of Strehler that should pass tests.
Actually, I think that the problem is a Dancer2 issue, I opened [this bug](https://github.com/PerlDancer/Dancer2/issues/1104) about it and I think that in the same time Daner2 developers [find it by themselves](https://github.com/PerlDancer/Dancer2/pull/1105).
However, i also found a workaround that works well so I used it in this new release.

**Comment by jahagirdar** [comment]
Thanks for the fix, Looks like there is some issue with the makefile.
the log file is as follows

---
make: Warning: File `Makefile.PL' has modification time 5.7e+04 s in the future
Makefile out-of-date with respect to Makefile.PL
Cleaning current config before rebuilding Makefile...
make -f Makefile.old clean > /dev/null 2>&1
"/home/starman/perl5/perlbrew/perls/perl-5.22.1/bin/perl" Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Strehler
Writing MYMETA.yml and MYMETA.json
==> Your Makefile has been rebuilt. <==
==> Please rerun the make command.  <==
false
make: *** [Makefile] Error 1
-> FAIL Installing Strehler failed. See /home/starman/.cpanm/work/1452898368.1705/build.log for details. Retry with --force to force install it.

**Comment by cym0n** [comment]
Mmmh, i tried to install the module from CPAN and I hadn't any problem.
That problem about "modification in the future" seems to me as something about your system clock.
I suggest you to remove package Strehler and try to install it again.

Is there something more about the problem in the build.log?

**Comment by jahagirdar** [comment]
I tired installing again in the evening and the installation went through, It might have been a timezone issue.
I will play around with the installation this weekend and provide my feedback on the same. 
Thanks and Regards
Vijay

**Comment by cym0n** [comment]
Perfect! I wait for your feedbacks!
Please use [the other issue](https://github.com/cym0n/strehler/issues/53) for any annotation, so that this closed bug can be kept closed :-)
