### ISSUE TITLE
Observation from Demo install

### ISSUE THREAD

**Issue by jahagirdar** [cym0n/strehler#55]
Ref: Instructions at http://search.cpan.org/dist/Strehler/lib/Strehler/Manual/Installation.pod

* Generated the demo site using `strehler demo`
 * This creates the proper app.pl but the app.psgi is not updated.
 * `perl bin/app.pl` works
* Copying the data from the app.pl to app.psgi and replacing `Site->dance` with `Site->to_app`
* Running `$ export DANCER_CONFDIR=`pwd`;plackup bin/app.psgi ` 
 * browsing to `http://192.168.1.7:5000/` shows the home template
* Browsing to `http://192.168.1.7:5000/admin` results in message of `Internal Server Error` followed by `file error - 404.tt: not found`

The console log is as follows

```
HTTP::Server::PSGI: Accepting connections at http://0:5000/
[Site:7882] core @2016-01-24 20:58:27> looking for get /admin in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1210
[Site:7882] core @2016-01-24 20:58:27> Entering hook core.error.init in (eval 61) l. 1
[Site:7882] core @2016-01-24 20:58:27> Entering hook core.error.before in (eval 61) l. 1
192.168.1.2 - - [24/Jan/2016:20:58:27 +0530] "GET /admin HTTP/1.1" 500 53 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0"
```
Will keep updating this ticket with other observations.

**Comment by jahagirdar** [comment]
The console log is as follows
```
HTTP::Server::PSGI: Accepting connections at http://0:5000/
[Site:7882] core @2016-01-24 20:58:27> looking for get /admin in /home/starman/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Dancer2/Core/App.pm l. 1210
[Site:7882] core @2016-01-24 20:58:27> Entering hook core.error.init in (eval 61) l. 1
[Site:7882] core @2016-01-24 20:58:27> Entering hook core.error.before in (eval 61) l. 1
192.168.1.2 - - [24/Jan/2016:20:58:27 +0530] "GET /admin HTTP/1.1" 500 53 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0"
```

**Comment by cym0n** [comment]
Lack of app.psgi file is my fault.  I didn't updated the demo version after Dancer2 development group introduced it in the framework.
However, I found that you can just use the app.pl file for plackup with no modifications and it works correctly.

```
export DANCER_CONFDIR=pwd;plackup bin/app.pl
```

**Comment by cym0n** [comment]
In Strehler 1.6.8, released today, demo creates also the app.psgi. As I said, is the same file of app.pl, for now.
Nearly in the future I want to review all my code considering latest Dancer2 improvements and probably I'll try to write it better then.
